name: liquid_vape
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'  # Ubah versi SDK sesuai dengan versi Flutter Anda

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/